import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import getBlogPages from "./getBlogPages";

export default function Home() {
  const blogPages = getBlogPages();
  console.log(blogPages);
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main className={styles.main}>
        lorum ipsum
        <div>
          <p>list of pages</p>
          <ul>
            {blogPages.map((b) => (
              <li key={b.path}>
                <Link href={b.path}>{b.fileName}</Link>
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
}

export const metadata = {
  title: "Wahid",
};
